export const FETCH_CARDS_PENDING = "FETCH_CARDS_PENDING";
export const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS";
export const FETCH_CARDS_FAILURE = "FETCH_CARDS_FAILURE";
export const FETCH_ACCESS_TOKEN_PENDING = "FETCH_ACCESS_TOKEN_PENDING";
export const FETCH_ACCESS_TOKEN_SUCCESS = "FETCH_ACCESS_TOKEN_SUCCESS";
export const FETCH_ACCESS_TOKEN_FAILURE = "FETCH_ACCESS_TOKEN_FAILURE";
